# Generated by Django 4.2.2 on 2023-08-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('DR', 'Dr'), ('MISS', 'Miss'), ('PROF', 'Prof')], max_length=255),
        ),
    ]
